---
title: "DP Expected Points"
description: |
  Expected Points modelling - last updated on `r as.character(Sys.Date())`.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# NFL Packages
library(nflreadr)
library(ffpros)

# Data Manipulation
library(dplyr)
library(janitor)
library(forcats)
library(stringr)
library(glue)

# Output Packages
library(reactable)
library(crosstalk)
library(htmltools)

ep <- nflreadr::load_ff_opportunity(2017:nflreadr::most_recent_season(), 
                                    stat_type = "weekly") |> 
  mutate(season = as.numeric(season)) |> 
  left_join(nflreadr::load_rosters(TRUE) |> select("pfr_id","gsis_id","season"),
            by = c("season","player_id"="gsis_id"),
            na_matches = "never") |> 
  left_join(nflreadr::load_snap_counts(TRUE) |> 
              select(pfr_player_id, season, week, offense_pct),
            by = c("season","pfr_id"="pfr_player_id","week")) |> 
  transmute(
    player_name = full_name,
    rank = "",
    week_num = week,
    week = as.character(week),
    pos = forcats::fct_relevel(position,c("QB","RB","WR","TE")),
    team = posteam,
    total_fantasy_points_exp,
    total_fantasy_points,
    total_fantasy_points_diff,
    total_yards_gained_exp,
    total_yards_gained,
    total_yards_gained_diff,
    total_touchdown_exp,
    total_touchdown,
    total_touchdown_diff,
    offense_pct,
    display = glue::glue("{full_name}, {pos} {team}"),
    season = as.character(season),
    player_id
  ) |> 
  group_by(season, player_id) |> 
  mutate(sort_by = -round(mean(total_fantasy_points_exp, na.rm = TRUE)),
         games_played = n()) |> 
  ungroup() |> 
  select(-player_id) |> 
  filter(pos %in% c("QB","RB","WR","TE")) |> 
  arrange(desc(season), sort_by) |> 
  janitor::clean_names("title") %>%
  rename_with(~ stringr::str_replace(.x, "Fantasy Points", "FP"))


crosstalk_ep <- crosstalk::SharedData$new(ep)
```



```{r layout = "l-page", fig.width = 16, fig.height = 16}
htmltools::tags$h3("Season Average Expected Points")

table_ep <- crosstalk_ep %>%
  reactable(
    striped = TRUE,
    highlight = TRUE,
    resizable = TRUE,
    compact = TRUE,
    # rownames = TRUE,
    groupBy = "Display",
    columns = list(
      `Display` = colDef(name = "Player", minWidth = 120, sticky = "left"),
      `Rank` = colDef(
        aggregated = JS(
          "function(cellInfo, state){
          return Number(cellInfo.viewIndex) + Number(state.page) * Number(state.pageSize) + 1
          }"
        )
      ),
      `Sort by` = colDef(show = FALSE),
      `Pos` = colDef(show = FALSE),
      `Team` = colDef(show = FALSE),
      `Week Num` = colDef(show = FALSE),
      `Player Name` = colDef(show = FALSE),
      `Games Played` = colDef(show = FALSE),
      `Week` = colDef(name = "Wk", minWidth = 40, format = colFormat(digits = 0)),
      `Total FP` = colDef(name = "Actual"),
      `Total Yards Gained` = colDef(name = "Actual"),
      `Total Touchdown` = colDef(name = "Actual"),
      `Total FP Exp` = colDef(name = "Exp"),
      `Total Yards Gained Exp` = colDef(name = "Exp"),
      `Total Touchdown Exp` = colDef(name = "Exp"),
      `Total FP Diff` = colDef(name = "Diff"),
      `Total Yards Gained Diff` = colDef(name = "Diff"),
      `Total Touchdown Diff` = colDef(name = "Diff"),
      `Offense Pct` = colDef(name = "Snap %", format = colFormat(percent = TRUE, digits = 0))
    ),
    columnGroups = list(
      colGroup(name = "Fantasy Points", c("Total FP","Total FP Exp", "Total FP Diff")),
      colGroup(name = "Yards", c("Total Yards Gained", "Total Yards Gained Exp", "Total Yards Gained Diff")),
      colGroup(name = "Touchdowns", c("Total Touchdown Exp", "Total Touchdown", "Total Touchdown Diff"))
    ),
    defaultColDef = colDef(minWidth = 60,
                           format = colFormat(digits = 1),
                           aggregate = "mean"),
    fullWidth = TRUE,
    defaultSortOrder = "asc",
    showSortIcon = FALSE,
    defaultSorted = c("Sort by", "Week Num"),
    defaultPageSize = 25,
    pageSizeOptions = c(25,50,100,500),
    showPageSizeOptions = TRUE
  )
```

```{r layout = "l-page", fig.width = 16, fig.height = 16}

# requires crosstalk#70

tags$details(
  class = "l-page",
  open = "",
  tags$summary(tags$strong("Filters")),
  bscols(
    widths = rep_len(4, 3),
    filter_select("player", "Player",crosstalk_ep, ~`Player Name`),
    filter_select("pos", "Position",crosstalk_ep, ~`Pos`),
    filter_select("team", "Team", crosstalk_ep, ~`Team`)
    ),
  bscols(
    widths = rep_len(3,4),
    filter_select("season", "Season", crosstalk_ep, ~Season, selected = "2023"),
    filter_slider("week", "Week", crosstalk_ep, ~`Week Num`, ticks = FALSE, step = 1),
    filter_slider("gp", "Games Played", crosstalk_ep, ~`Games Played`, ticks = FALSE,step = 1),
    filter_slider("ep", "EP", crosstalk_ep, ~-`Sort by`, ticks = FALSE, step = 0.5)
  )

)
table_ep
```
